pub mod build;
pub mod bundle;
pub mod dev;
pub mod doctor;
pub mod self_test;

use std::path::{Path, PathBuf};

use crate::cli::{NewArgs, NewTemplate};
use crate::error::AxionCliError;

const TEMPLATE_APP_ICON: &[u8] = include_bytes!("../../assets/app.icns");

pub fn run_new(args: NewArgs) -> Result<(), AxionCliError> {
    let project = NewProject::new(args)?;
    project.write()?;

    println!("Axion application created");
    println!("name: {}", project.name);
    println!("template: {}", project.template.name());
    println!("path: {}", project.root.display());
    Ok(())
}

#[derive(Debug, Clone)]
struct NewProject {
    name: String,
    root: PathBuf,
    axion_root: PathBuf,
    template: NewTemplate,
}

impl NewProject {
    fn new(args: NewArgs) -> Result<Self, AxionCliError> {
        let name = normalize_project_name(&args.name);
        let axion_root = axion_root_for_templates()?;
        let current_dir = std::env::current_dir()?;
        let root = args.path.unwrap_or_else(|| current_dir.join(&name));

        Ok(Self {
            name,
            root,
            axion_root,
            template: args.template,
        })
    }

    fn write(&self) -> Result<(), AxionCliError> {
        if self.root.exists() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::AlreadyExists,
                format!("project path already exists: {}", self.root.display()),
            )
            .into());
        }

        std::fs::create_dir_all(self.root.join("src"))?;
        std::fs::create_dir_all(self.root.join("frontend"))?;
        std::fs::create_dir_all(self.root.join("icons"))?;
        std::fs::write(self.root.join("Cargo.toml"), self.cargo_toml())?;
        std::fs::write(self.root.join(".gitignore"), self.gitignore())?;
        std::fs::write(self.root.join("README.md"), self.readme())?;
        std::fs::write(self.root.join("axion.toml"), self.manifest())?;
        std::fs::write(self.root.join("icons").join("app.icns"), TEMPLATE_APP_ICON)?;
        std::fs::write(self.root.join("src").join("main.rs"), self.main_rs())?;
        std::fs::write(
            self.root.join("frontend").join("index.html"),
            self.index_html(),
        )?;
        std::fs::write(
            self.root.join("frontend").join("style.css"),
            self.style_css(),
        )?;
        std::fs::write(self.root.join("frontend").join("app.js"), self.app_js())?;
        Ok(())
    }

    fn readme(&self) -> String {
        format!(
            "# {title}\n\nGenerated by Axion using the `{template}` template.\n\n## Run\n\n```sh\ncargo run -- --plan\ncargo run --features servo-runtime\n```\n\n## What The Demo Shows\n\n- Bridge availability, allowed commands, frontend events, and host events.\n- Built-in app/window commands: `app.info`, `app.version`, `app.echo`, and `window.info`.\n- Native preview APIs: `fs.write_text`, `fs.read_text`, `dialog.open`, and `dialog.save`.\n- A custom Rust command, `demo.greet`, registered in `src/main.rs`.\n- Capability denial behavior through an intentional `demo.missing` call.\n- Bundle icon validation through `[bundle] icon = \"icons/app.icns\"`.\n\n## Runtime Artifacts\n\nRuntime data, staged bundles, and crash reports are written under `target/` and ignored by `.gitignore`. Panic reports are installed in `src/main.rs` and written to `target/axion/crash-reports/`.\n\n## Custom Command Demo\n\nThis template registers `demo.greet` in `src/main.rs`, allows it in `axion.toml`, and calls it from `frontend/app.js`. New commands must return JSON text and must be listed in the active window capability before frontend code can invoke them.\n\n## Validate From Axion Checkout\n\n```sh\ncargo run -p axion-cli -- doctor --manifest-path {manifest}\ncargo run -p axion-cli -- self-test --manifest-path {manifest}\ncargo run -p axion-cli -- bundle --manifest-path {manifest} --build-executable\n```\n\n## Project Layout\n\n- `.gitignore`: local build and Axion runtime artifacts\n- `axion.toml`: app manifest, bundle icon, and per-window capabilities\n- `icons/app.icns`: bundled application icon\n- `src/main.rs`: Rust entrypoint, panic reporter, and custom command plugin\n- `frontend/index.html`: packaged HTML entry\n- `frontend/style.css`: CSP-compatible external styles\n- `frontend/app.js`: bridge, native API, event, and capability-denial demos\n",
            title = title_case(&self.name),
            template = self.template.name(),
            manifest = self.root.join("axion.toml").display(),
        )
    }

    fn gitignore(&self) -> String {
        "target/\n.DS_Store\n*.log\n".to_owned()
    }

    fn cargo_toml(&self) -> String {
        format!(
            "[package]\nname = {name:?}\nversion = \"0.1.4\"\nedition = \"2024\"\nrust-version = \"1.86.0\"\n\n[features]\ndefault = []\nservo-runtime = [\"axion-runtime/servo-runtime\"]\n\n[dependencies]\naxion-core = {{ path = {core:?} }}\naxion-manifest = {{ path = {manifest:?} }}\naxion-runtime = {{ path = {runtime:?} }}\n",
            name = self.name,
            core = self
                .axion_root
                .join("crates")
                .join("axion-core")
                .display()
                .to_string(),
            manifest = self
                .axion_root
                .join("crates")
                .join("axion-manifest")
                .display()
                .to_string(),
            runtime = self
                .axion_root
                .join("crates")
                .join("axion-runtime")
                .display()
                .to_string(),
        )
    }

    fn manifest(&self) -> String {
        format!(
            "[app]\nname = {name:?}\nidentifier = \"dev.axion.{identifier}\"\nversion = \"0.1.0\"\ndescription = \"Generated Axion application\"\nauthors = [\"Axion Developer\"]\nhomepage = \"https://example.dev/{name}\"\n\n[window]\nid = \"main\"\ntitle = {title:?}\nwidth = 960\nheight = 720\nresizable = true\nvisible = true\n\n[build]\nfrontend_dist = \"frontend\"\nentry = \"frontend/index.html\"\n\n[bundle]\nicon = \"icons/app.icns\"\n\n[native.dialog]\nbackend = \"headless\"\n\n[capabilities.main]\ncommands = [\"app.ping\", \"app.info\", \"app.version\", \"app.echo\", \"window.info\", \"fs.write_text\", \"fs.read_text\", \"dialog.open\", \"dialog.save\", \"demo.greet\"]\nevents = [\"app.log\"]\nprotocols = [\"axion\"]\nallowed_navigation_origins = []\nallow_remote_navigation = false\n",
            name = self.name,
            identifier = self.name.replace('-', "."),
            title = title_case(&self.name),
        )
    }

    fn main_rs(&self) -> String {
        r#"use std::path::Path;

use axion_core::{Builder, RunMode};

#[cfg(feature = "servo-runtime")]
struct DemoPlugin;

#[cfg(feature = "servo-runtime")]
impl axion_runtime::RuntimePlugin for DemoPlugin {
    fn register(&self, builder: &mut axion_runtime::RuntimeBridgeBindingsBuilder) {
        builder.register_command("demo.greet", |context, request| {
            Ok(format!(
                "{{\"message\":{},\"appName\":{},\"windowId\":{},\"payload\":{}}}",
                axion_runtime::json_string_literal("Hello from a custom Rust command"),
                axion_runtime::json_string_literal(&context.app_name),
                axion_runtime::json_string_literal(&context.window.id),
                request.payload,
            ))
        });

        builder.push_startup_event(axion_runtime::RuntimeBridgeEvent::new(
            "demo.ready",
            "{\"source\":\"demo-plugin\"}",
        ));
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("axion.toml");
    let config = axion_manifest::load_app_config_from_path(&manifest_path)?;
    let app = Builder::new().apply_config(config).build()?;
    axion_runtime::install_panic_reporter(axion_runtime::PanicReportConfig {
        app_name: app.config().identity.name.clone(),
        output_dir: Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("axion")
            .join("crash-reports"),
    });

    if std::env::args().skip(1).any(|arg| arg == "--plan") {
        println!("{plan}", plan = app.runtime_plan(RunMode::Production));
        return Ok(());
    }

    #[cfg(not(feature = "servo-runtime"))]
    {
        Err(std::io::Error::other(
            "Servo runtime is disabled; rebuild with `--features servo-runtime` or run with `--plan`",
        )
        .into())
    }

    #[cfg(feature = "servo-runtime")]
    {
        let demo_plugin = DemoPlugin;
        let plugins: [&dyn axion_runtime::RuntimePlugin; 1] = [&demo_plugin];
        axion_runtime::run_with_plugins(app, RunMode::Production, &plugins)?;
        Ok(())
    }
}
"#
        .to_owned()
    }

    fn index_html(&self) -> String {
        format!(
            "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <title>{title}</title>\n    <link rel=\"stylesheet\" href=\"style.css\">\n  </head>\n  <body>\n    <main class=\"shell\">\n      <section class=\"hero\">\n        <p class=\"eyebrow\">Axion Vanilla Template</p>\n        <h1>{title}</h1>\n        <p id=\"bridge-status\" class=\"status\">Waiting for Axion bridge...</p>\n      </section>\n\n      <section class=\"grid\">\n        <article class=\"card\">\n          <h2>Bridge Surface</h2>\n          <p>Commands exposed to this window:</p>\n          <ul id=\"command-list\"></ul>\n          <p>Frontend events:</p>\n          <ul id=\"event-list\"></ul>\n          <p>Host events:</p>\n          <ul id=\"host-event-list\"></ul>\n        </article>\n\n        <article class=\"card\">\n          <h2>App & Window API</h2>\n          <pre id=\"app-info\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Native Preview APIs</h2>\n          <pre id=\"native-api\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Custom Rust Command</h2>\n          <pre id=\"custom-command\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Capability Denial</h2>\n          <pre id=\"capability-denial\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Event Log</h2>\n          <pre id=\"event-log\">Waiting...</pre>\n        </article>\n      </section>\n    </main>\n    <script src=\"app.js\"></script>\n  </body>\n</html>\n",
            title = title_case(&self.name),
        )
    }

    fn style_css(&self) -> String {
        r#":root {
  color-scheme: light dark;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #111827;
  color: #e5e7eb;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(45, 212, 191, 0.18), transparent 30rem),
    linear-gradient(135deg, #111827 0%, #1f2937 55%, #0f172a 100%);
}

.shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 48px 0;
}

.hero {
  margin-bottom: 24px;
}

.eyebrow {
  margin: 0 0 8px;
  color: #5eead4;
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

h1,
h2,
p {
  margin-top: 0;
}

h1 {
  margin-bottom: 12px;
  font-size: clamp(2rem, 5vw, 4rem);
}

h2 {
  font-size: 1rem;
}

.status {
  display: inline-flex;
  border: 1px solid rgba(94, 234, 212, 0.35);
  border-radius: 999px;
  padding: 8px 14px;
  background: rgba(15, 23, 42, 0.72);
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
}

.card {
  border: 1px solid rgba(148, 163, 184, 0.2);
  border-radius: 18px;
  padding: 18px;
  background: rgba(15, 23, 42, 0.78);
  box-shadow: 0 24px 80px rgba(15, 23, 42, 0.32);
}

ul {
  margin: 0 0 16px;
  padding-left: 18px;
}

li {
  margin: 4px 0;
}

pre {
  overflow: auto;
  min-height: 72px;
  margin: 0;
  border-radius: 12px;
  padding: 12px;
  background: rgba(2, 6, 23, 0.7);
  color: #bfdbfe;
  white-space: pre-wrap;
}
"#
        .to_owned()
    }

    fn app_js(&self) -> String {
        r#"window.addEventListener('DOMContentLoaded', async () => {
  const appName = '@APP_NAME@';
  const status = document.getElementById('bridge-status');

  function renderList(id, values) {
    const list = document.getElementById(id);
    list.textContent = '';
    for (const value of values) {
      const item = document.createElement('li');
      item.textContent = value;
      list.appendChild(item);
    }
  }

  function renderJson(id, value) {
    document.getElementById(id).textContent = JSON.stringify(value, null, 2);
  }

  function renderText(id, value) {
    document.getElementById(id).textContent = value;
  }

  if (!window.__AXION__) {
    status.textContent = 'Axion bootstrap was not injected. Run with `cargo run --features servo-runtime`.';
    for (const id of ['app-info', 'native-api', 'custom-command', 'capability-denial', 'event-log']) {
      renderText(id, 'Bridge unavailable');
    }
    return;
  }

  const axion = window.__AXION__;
  renderList('command-list', axion.commands);
  renderList('event-list', axion.events);
  renderList('host-event-list', axion.hostEvents);

  try {
    const pluginReady = new Promise((resolve) => {
      const timeout = window.setTimeout(() => resolve({ source: 'demo-plugin', observed: false }), 1500);
      axion.listen('demo.ready', (payload) => {
        window.clearTimeout(timeout);
        resolve({ source: payload.source, observed: true });
      });
    });

    const [ping, appInfo, appVersion, appEcho, windowInfo] = await Promise.all([
      axion.invoke('app.ping', { from: appName }),
      axion.invoke('app.info', null),
      axion.invoke('app.version', null),
      axion.invoke('app.echo', { from: appName, async: true }),
      axion.invoke('window.info', null),
    ]);

    renderJson('app-info', { ping, appInfo, appVersion, appEcho, windowInfo });

    const fsWrite = await axion.invoke('fs.write_text', {
      path: 'notes/hello.txt',
      contents: `${appName} wrote this through the Axion bridge`,
    });
    const fsRead = await axion.invoke('fs.read_text', { path: 'notes/hello.txt' });
    const dialogOpen = await axion.invoke('dialog.open', {
      title: 'Select files for the Axion preview',
      multiple: true,
      filters: [
        { name: 'Text', extensions: ['txt', 'md'] },
        { name: 'Images', extensions: ['png', 'jpg'] },
      ],
    });
    const dialogSave = await axion.invoke('dialog.save', {
      title: 'Choose a save path for the Axion preview',
      defaultPath: 'notes/export.txt',
    });
    renderJson('native-api', { fsWrite, fsRead, dialogOpen, dialogSave });

    const [greeting, pluginEvent] = await Promise.all([
      axion.invoke('demo.greet', { from: `${appName}-frontend` }),
      pluginReady,
    ]);
    renderJson('custom-command', { greeting, pluginEvent });

    const deniedCommand = await axion.invoke('demo.missing', null)
      .then(() => 'unexpected success')
      .catch((error) => error instanceof Error ? error.message : String(error));
    renderJson('capability-denial', {
      attemptedCommand: 'demo.missing',
      result: deniedCommand,
      explanation: 'Commands must be registered and allowed in axion.toml before frontend code can invoke them.',
    });

    const hostLog = axion.events.includes('app.log')
      ? await axion.emit('app.log', { message: `${appName} frontend is ready`, windowId: windowInfo.id })
      : false;
    renderJson('event-log', {
      emitted: hostLog,
      frontendEvents: axion.events,
      hostEvents: axion.hostEvents,
    });

    status.textContent = `Axion bridge ready: ${ping.message} from ${ping.appName}; custom=${greeting.message}`;
  } catch (error) {
    status.textContent = `Axion invoke failed: ${error instanceof Error ? error.message : String(error)}`;
    renderText('event-log', status.textContent);
  }
});
"#
        .replace("@APP_NAME@", &self.name)
    }
}

impl NewTemplate {
    fn name(self) -> &'static str {
        match self {
            Self::Vanilla => "vanilla",
        }
    }
}

fn axion_root_for_templates() -> Result<PathBuf, AxionCliError> {
    let cli_manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    if let Some(axion_root) = cli_manifest_dir
        .parent()
        .and_then(Path::parent)
        .filter(|path| path.join("crates").join("axion-core").exists())
    {
        return Ok(axion_root.to_path_buf());
    }

    Ok(std::env::current_dir()?)
}

fn normalize_project_name(name: &str) -> String {
    let normalized = name
        .trim()
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '-' {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_owned();

    if normalized.is_empty() {
        "axion-app".to_owned()
    } else {
        normalized
    }
}

fn title_case(name: &str) -> String {
    name.split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::{NewProject, axion_root_for_templates, normalize_project_name, title_case};
    use crate::cli::NewTemplate;

    #[test]
    fn project_name_is_normalized_for_package_use() {
        assert_eq!(normalize_project_name("Hello Axion!"), "hello-axion");
        assert_eq!(normalize_project_name("  "), "axion-app");
    }

    #[test]
    fn title_case_expands_kebab_name() {
        assert_eq!(title_case("hello-axion"), "Hello Axion");
    }

    #[test]
    fn template_axion_root_points_at_checkout_root() {
        let root = axion_root_for_templates().expect("template root should resolve");
        assert!(root.join("crates").join("axion-core").exists());
    }

    #[test]
    fn generated_frontend_uses_external_script_for_csp() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("unused"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        assert!(
            project
                .index_html()
                .contains("<script src=\"app.js\"></script>")
        );
        assert!(
            project
                .index_html()
                .contains("<link rel=\"stylesheet\" href=\"style.css\">")
        );
        assert!(!project.index_html().contains("window.addEventListener"));
        assert!(project.app_js().contains("window.addEventListener"));
        assert!(project.app_js().contains("axion.emit('app.log'"));
        assert!(project.app_js().contains("axion.invoke('demo.greet'"));
        assert!(project.app_js().contains("axion.invoke('demo.missing'"));
        assert!(project.app_js().contains("dialog.open"));
        assert!(project.app_js().contains("dialog.save"));
        assert!(project.style_css().contains(".grid"));
    }

    #[test]
    fn generated_project_includes_custom_command_plugin() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("unused"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        assert!(project.manifest().contains("\"demo.greet\""));
        assert!(project.manifest().contains("\"dialog.open\""));
        assert!(project.manifest().contains("\"dialog.save\""));
        assert!(project.manifest().contains("[bundle]"));
        assert!(project.manifest().contains("icon = \"icons/app.icns\""));
        assert!(project.manifest().contains("[native.dialog]"));
        assert!(project.manifest().contains("backend = \"headless\""));
        assert!(project.main_rs().contains("struct DemoPlugin"));
        assert!(
            project
                .main_rs()
                .contains("register_command(\"demo.greet\"")
        );
        assert!(project.main_rs().contains("run_with_plugins"));
        assert!(project.main_rs().contains("json_string_literal"));
        assert!(project.main_rs().contains("install_panic_reporter"));
        assert!(project.main_rs().contains("target"));
        assert!(project.main_rs().contains("crash-reports"));
    }

    #[test]
    fn generated_project_readme_documents_template_and_commands() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("/tmp/hello-axion"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        let readme = project.readme();
        assert!(readme.contains("Generated by Axion using the `vanilla` template."));
        assert!(readme.contains("cargo run -- --plan"));
        assert!(readme.contains("cargo run --features servo-runtime"));
        assert!(readme.contains("cargo run -p axion-cli -- bundle"));
        assert!(readme.contains("--build-executable"));
        assert!(readme.contains("Custom Command Demo"));
        assert!(readme.contains("demo.greet"));
        assert!(readme.contains("Capability denial"));
        assert!(readme.contains("frontend/style.css"));
        assert!(readme.contains("dialog.open"));
        assert!(readme.contains("Runtime Artifacts"));
        assert!(readme.contains("target/axion/crash-reports/"));
        assert!(readme.contains(".gitignore"));
        assert!(readme.contains("icons/app.icns"));
    }

    #[test]
    fn generated_project_template_includes_icon_asset() {
        assert!(super::TEMPLATE_APP_ICON.starts_with(b"icns"));
    }

    #[test]
    fn generated_project_gitignore_covers_local_artifacts() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("unused"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        let gitignore = project.gitignore();
        assert!(gitignore.lines().any(|line| line == "target/"));
        assert!(gitignore.lines().any(|line| line == ".DS_Store"));
        assert!(gitignore.lines().any(|line| line == "*.log"));
    }
}
