pub mod build;
pub mod bundle;
pub mod check;
pub mod dev;
pub mod doctor;
pub mod gui_smoke;
pub mod release;
pub mod self_test;

use std::path::{Path, PathBuf};

use crate::cli::{CheckArgs, DoctorRisk, NewArgs, NewTemplate};
use crate::error::AxionCliError;

const TEMPLATE_APP_ICON: &[u8] = include_bytes!("../../assets/app.icns");

pub fn run_new(args: NewArgs) -> Result<(), AxionCliError> {
    let run_check = args.run_check;
    let project = NewProject::new(args)?;
    project.write()?;

    println!("Axion application created");
    println!("name: {}", project.name);
    println!("template: {}", project.template.name());
    println!("path: {}", project.root.display());
    println!("next:");
    println!("  cd {}", project.root.display());
    println!("  cargo run -- --plan");
    println!(
        "  cargo run -p axion-cli -- check --manifest-path {} --bundle",
        project.root.join("axion.toml").display()
    );
    println!("  cargo run --features servo-runtime");
    if run_check {
        println!("running initial check:");
        check::run(CheckArgs {
            manifest_path: project.root.join("axion.toml"),
            max_risk: DoctorRisk::Medium,
            bundle: true,
            json: false,
            keep_artifacts: false,
        })?;
    }
    Ok(())
}

#[derive(Debug, Clone)]
struct NewProject {
    name: String,
    root: PathBuf,
    axion_root: PathBuf,
    template: NewTemplate,
}

impl NewProject {
    fn new(args: NewArgs) -> Result<Self, AxionCliError> {
        let name = normalize_project_name(&args.name);
        let axion_root = axion_root_for_templates()?;
        let current_dir = std::env::current_dir()?;
        let root = args.path.unwrap_or_else(|| current_dir.join(&name));

        Ok(Self {
            name,
            root,
            axion_root,
            template: args.template,
        })
    }

    fn write(&self) -> Result<(), AxionCliError> {
        if self.root.exists() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::AlreadyExists,
                format!("project path already exists: {}", self.root.display()),
            )
            .into());
        }

        std::fs::create_dir_all(self.root.join("src"))?;
        std::fs::create_dir_all(self.root.join("frontend"))?;
        std::fs::create_dir_all(self.root.join("icons"))?;
        std::fs::write(self.root.join("Cargo.toml"), self.cargo_toml())?;
        std::fs::write(self.root.join(".gitignore"), self.gitignore())?;
        std::fs::write(self.root.join("README.md"), self.readme())?;
        std::fs::write(self.root.join("axion.toml"), self.manifest())?;
        std::fs::write(self.root.join("icons").join("app.icns"), TEMPLATE_APP_ICON)?;
        std::fs::write(self.root.join("src").join("main.rs"), self.main_rs())?;
        std::fs::write(
            self.root.join("frontend").join("index.html"),
            self.index_html(),
        )?;
        std::fs::write(
            self.root.join("frontend").join("style.css"),
            self.style_css(),
        )?;
        std::fs::write(self.root.join("frontend").join("app.js"), self.app_js())?;
        Ok(())
    }

    fn readme(&self) -> String {
        format!(
            r#"# {title}

Generated by Axion using the `{template}` template.

## Run

```sh
cargo run -- --plan
cargo run --features servo-runtime
```

## Frontend Development

This template has no npm dependency by default. To use your own frontend dev server, add a `[dev]` URL to `axion.toml`, start that server separately, then launch from the Axion checkout:

```sh
cargo run -p axion-cli -- dev --manifest-path {manifest}
cargo run -p axion-cli --features servo-runtime -- dev --manifest-path {manifest} --launch
```

If the dev server is unavailable, use `--fallback-packaged` to launch the packaged `frontend/index.html` entry instead. `--watch` polls frontend files with debounce and temporary-file ignore rules, and `--reload` asks live windows to reload when launched with `--launch`. `--open-devtools` reports that the current Servo backend does not open devtools yet.

```sh
cargo run -p axion-cli --features servo-runtime -- dev --manifest-path {manifest} --launch --fallback-packaged --watch --reload
```

## What The Demo Shows

- Bridge availability, allowed commands, frontend events, and host lifecycle events such as `window.ready`.
- Built-in app/window commands: `app.info`, `app.version`, `app.echo`, `window.info`, `window.reload`, `window.set_title`, and `window.set_size`.
- Native preview APIs: `fs.write_text`, `fs.read_text`, `dialog.open`, and `dialog.save`.
- A custom Rust command, `demo.greet`, registered in `src/main.rs`.
- Capability denial behavior through an intentional `demo.missing` call.
- Bundle icon validation through `[bundle] icon = "icons/app.icns"`.
- A text-input compatibility panel that demonstrates `window.__AXION__.compat.installTextInputSelectionPatch`.
- A `window.__AXION_GUI_SMOKE__()` hook for Servo-backed GUI smoke diagnostics.

## Packaging Preview

`axion bundle` creates a platform bundle scaffold, copies `frontend/`, writes app metadata, copies `icons/app.icns`, emits `axion-bundle-manifest.json`, and verifies file references plus fingerprints. It is a staging bundle, not a signed installer.

```sh
cargo run -p axion-cli -- bundle --manifest-path {manifest} --build-executable
cargo run -p axion-cli -- bundle --manifest-path {manifest} --build-executable --json --report-path target/axion/reports/bundle.json
cargo run -p axion-cli -- release --manifest-path {manifest} --json --report-path target/axion/reports/release.json --bundle-report-path target/axion/reports/bundle.json --archive --archive-path target/axion/reports/bundle.tar
```

Expected output includes `target`, `layout`, `bundle_dir`, `bundle_manifest`, `platform_metadata`, `verification: ok`, `checked_files`, `fingerprinted_files`, and `bundle_bytes`. JSON output uses `axion.bundle-report.v1` for scripted release checks and can be written with `--report-path`. Release JSON uses `axion.release-report.v1` and includes `artifacts[]`, `failure_phase`, `failed_reasons`, and archive verification details.

## Runtime Artifacts

Runtime data, staged bundles, and crash reports are written under `target/` and ignored by `.gitignore`. Panic reports are installed in `src/main.rs` and written to `target/axion/crash-reports/`.

## Custom Command Demo

This template registers `demo.greet` in `src/main.rs`, allows it in `axion.toml`, and calls it from `frontend/app.js`. New commands must return JSON text and must be listed in the active window capability before frontend code can invoke them.

## Input Compatibility Demo

The generated frontend includes a small text input and textarea wired to `window.__AXION__.compat.installTextInputSelectionPatch`. Use it when you need more stable caret placement or drag selection in Servo-backed text controls.

## Validate From Axion Checkout

Run these commands from the Axion repository root so `gui-smoke` can reuse the checkout build cache through `--cargo-target-dir target`:

```sh
cargo run -p axion-cli -- check --manifest-path {manifest} --bundle
cargo run -p axion-cli -- doctor --manifest-path {manifest} --deny-warnings --max-risk medium
cargo run -p axion-cli -- self-test --manifest-path {manifest}
cargo run -p axion-cli -- gui-smoke --manifest-path {manifest} --report-path target/axion/reports/gui-smoke.json --timeout-ms 30000 --cargo-target-dir target --serial-build
cargo run -p axion-cli -- bundle --manifest-path {manifest} --build-executable
cargo run -p axion-cli -- bundle --manifest-path {manifest} --build-executable --json --report-path target/axion/reports/bundle.json
cargo run -p axion-cli -- release --manifest-path {manifest} --json --report-path target/axion/reports/release.json --bundle-report-path target/axion/reports/bundle.json --archive --archive-path target/axion/reports/bundle.tar
```

## Project Layout

- `.gitignore`: local build and Axion runtime artifacts
- `axion.toml`: app manifest, optional dev server notes, bundle icon, and per-window capability profiles
- `icons/app.icns`: bundled application icon
- `src/main.rs`: Rust entrypoint, panic reporter, and custom command plugin
- `frontend/index.html`: packaged HTML entry
- `frontend/style.css`: CSP-compatible external styles
- `frontend/app.js`: bridge, native API, input-compatibility, event, capability-denial, and GUI smoke demos
"#,
            title = title_case(&self.name),
            template = self.template.name(),
            manifest = self.root.join("axion.toml").display(),
        )
    }

    fn gitignore(&self) -> String {
        "target/\n.DS_Store\n*.log\n".to_owned()
    }

    fn cargo_toml(&self) -> String {
        format!(
            "[package]\nname = {name:?}\nversion = \"0.1.16\"\nedition = \"2024\"\nrust-version = \"1.86.0\"\n\n[features]\ndefault = []\nservo-runtime = [\"axion-runtime/servo-runtime\"]\n\n[dependencies]\naxion-core = {{ path = {core:?} }}\naxion-manifest = {{ path = {manifest:?} }}\naxion-runtime = {{ path = {runtime:?} }}\n",
            name = self.name,
            core = self
                .axion_root
                .join("crates")
                .join("axion-core")
                .display()
                .to_string(),
            manifest = self
                .axion_root
                .join("crates")
                .join("axion-manifest")
                .display()
                .to_string(),
            runtime = self
                .axion_root
                .join("crates")
                .join("axion-runtime")
                .display()
                .to_string(),
        )
    }

    fn manifest(&self) -> String {
        format!(
            "[app]\nname = {name:?}\nidentifier = \"dev.axion.{identifier}\"\nversion = \"0.1.0\"\ndescription = \"Generated Axion application\"\nauthors = [\"Axion Developer\"]\nhomepage = \"https://example.dev/{name}\"\n\n[window]\nid = \"main\"\ntitle = {title:?}\nwidth = 960\nheight = 720\nresizable = true\nvisible = true\n\n[build]\nfrontend_dist = \"frontend\"\nentry = \"frontend/index.html\"\n\n# To use `axion dev --launch` with a frontend dev server, uncomment and update:\n# [dev]\n# url = \"http://127.0.0.1:3000\"\n# command = \"python3 -m http.server 3000 --bind 127.0.0.1 --directory frontend\"\n# timeout_ms = 15000\n\n[bundle]\nicon = \"icons/app.icns\"\n\n[native.dialog]\nbackend = \"headless\"\n\n[capabilities.main]\nprofiles = [\"app-info\", \"window-control\", \"file-access\", \"dialog-access\", \"app-events\"]\ncommands = [\"demo.greet\"]\nallowed_navigation_origins = []\nallow_remote_navigation = false\n",
            name = self.name,
            identifier = self.name.replace('-', "."),
            title = title_case(&self.name),
        )
    }

    fn main_rs(&self) -> String {
        r#"use std::path::Path;

use axion_core::{Builder, RunMode};

#[cfg(feature = "servo-runtime")]
struct DemoPlugin;

#[cfg(feature = "servo-runtime")]
impl axion_runtime::RuntimePlugin for DemoPlugin {
    fn register(&self, builder: &mut axion_runtime::RuntimeBridgeBindingsBuilder) {
        builder.register_command("demo.greet", |context, request| {
            Ok(format!(
                "{{\"message\":{},\"appName\":{},\"windowId\":{},\"payload\":{}}}",
                axion_runtime::json_string_literal("Hello from a custom Rust command"),
                axion_runtime::json_string_literal(&context.app_name),
                axion_runtime::json_string_literal(&context.window.id),
                request.payload,
            ))
        });

        builder.push_startup_event(axion_runtime::RuntimeBridgeEvent::new(
            "demo.ready",
            "{\"source\":\"demo-plugin\"}",
        ));
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("axion.toml");
    let config = axion_manifest::load_app_config_from_path(&manifest_path)?;
    let app = Builder::new().apply_config(config).build()?;
    axion_runtime::install_panic_reporter(axion_runtime::PanicReportConfig {
        app_name: app.config().identity.name.clone(),
        output_dir: Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("axion")
            .join("crash-reports"),
    });

    if std::env::args().skip(1).any(|arg| arg == "--plan") {
        println!("{plan}", plan = app.runtime_plan(RunMode::Production));
        return Ok(());
    }

    #[cfg(not(feature = "servo-runtime"))]
    {
        Err(std::io::Error::other(
            "Servo runtime is disabled; rebuild with `--features servo-runtime` or run with `--plan`",
        )
        .into())
    }

    #[cfg(feature = "servo-runtime")]
    {
        let demo_plugin = DemoPlugin;
        let plugins: [&dyn axion_runtime::RuntimePlugin; 1] = [&demo_plugin];
        axion_runtime::run_with_plugins(app, RunMode::Production, &plugins)?;
        Ok(())
    }
}
"#
        .to_owned()
    }

    fn index_html(&self) -> String {
        format!(
            "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <title>{title}</title>\n    <link rel=\"stylesheet\" href=\"style.css\">\n  </head>\n  <body>\n    <main class=\"shell\">\n      <section class=\"hero\">\n        <p class=\"eyebrow\">Axion Vanilla Template</p>\n        <h1>{title}</h1>\n        <p id=\"bridge-status\" class=\"status\">Waiting for Axion bridge...</p>\n      </section>\n\n      <section class=\"grid\">\n        <article class=\"card\">\n          <h2>Bridge Surface</h2>\n          <p>Commands exposed to this window:</p>\n          <ul id=\"command-list\"></ul>\n          <p>Frontend events:</p>\n          <ul id=\"event-list\"></ul>\n          <p>Host events:</p>\n          <ul id=\"host-event-list\"></ul>\n        </article>\n\n        <article class=\"card\">\n          <h2>App & Window API</h2>\n          <pre id=\"app-info\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Native Preview APIs</h2>\n          <pre id=\"native-api\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Input Compatibility</h2>\n          <label class=\"field\">\n            <span>Sample Input</span>\n            <input id=\"compat-input\" type=\"text\" value=\"Axion caret placement demo\">\n          </label>\n          <label class=\"field\">\n            <span>Sample Textarea</span>\n            <textarea id=\"compat-textarea\" rows=\"5\">Try clicking, selecting, and pressing Tab here.\nThe template wires this textarea to Axion's text selection compatibility helper.</textarea>\n          </label>\n          <pre id=\"compat-diagnostics\">Waiting for text input interaction...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Custom Rust Command</h2>\n          <pre id=\"custom-command\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Capability Denial</h2>\n          <pre id=\"capability-denial\">Waiting...</pre>\n        </article>\n\n        <article class=\"card\">\n          <h2>Event Log</h2>\n          <pre id=\"event-log\">Waiting...</pre>\n        </article>\n      </section>\n    </main>\n    <script src=\"app.js\"></script>\n  </body>\n</html>\n",
            title = title_case(&self.name),
        )
    }

    fn style_css(&self) -> String {
        r#":root {
  color-scheme: light dark;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #111827;
  color: #e5e7eb;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(45, 212, 191, 0.18), transparent 30rem),
    linear-gradient(135deg, #111827 0%, #1f2937 55%, #0f172a 100%);
}

.shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 48px 0;
}

.hero {
  margin-bottom: 24px;
}

.eyebrow {
  margin: 0 0 8px;
  color: #5eead4;
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

h1,
h2,
p {
  margin-top: 0;
}

h1 {
  margin-bottom: 12px;
  font-size: clamp(2rem, 5vw, 4rem);
}

h2 {
  font-size: 1rem;
}

.status {
  display: inline-flex;
  border: 1px solid rgba(94, 234, 212, 0.35);
  border-radius: 999px;
  padding: 8px 14px;
  background: rgba(15, 23, 42, 0.72);
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
}

.card {
  border: 1px solid rgba(148, 163, 184, 0.2);
  border-radius: 18px;
  padding: 18px;
  background: rgba(15, 23, 42, 0.78);
  box-shadow: 0 24px 80px rgba(15, 23, 42, 0.32);
}

ul {
  margin: 0 0 16px;
  padding-left: 18px;
}

li {
  margin: 4px 0;
}

pre {
  overflow: auto;
  min-height: 72px;
  margin: 0;
  border-radius: 12px;
  padding: 12px;
  background: rgba(2, 6, 23, 0.7);
  color: #bfdbfe;
  white-space: pre-wrap;
}

.field {
  display: block;
  margin-bottom: 12px;
}

.field span {
  display: block;
  margin-bottom: 6px;
  color: #cbd5e1;
  font-size: 0.92rem;
}

input,
textarea {
  width: 100%;
  border: 1px solid rgba(148, 163, 184, 0.28);
  border-radius: 12px;
  padding: 10px 12px;
  background: rgba(2, 6, 23, 0.72);
  color: #e2e8f0;
  font: inherit;
  font-family: ui-monospace, "SFMono-Regular", "SF Mono", Menlo, monospace;
  line-height: 1.4;
}

textarea {
  resize: vertical;
  tab-size: 2;
}
"#
        .to_owned()
    }

    fn app_js(&self) -> String {
        r#"window.addEventListener('DOMContentLoaded', async () => {
  const appName = '@APP_NAME@';
  const status = document.getElementById('bridge-status');
  const compatInput = document.getElementById('compat-input');
  const compatTextarea = document.getElementById('compat-textarea');
  const compatDiagnostics = document.getElementById('compat-diagnostics');

  function renderList(id, values) {
    const list = document.getElementById(id);
    list.textContent = '';
    for (const value of values) {
      const item = document.createElement('li');
      item.textContent = value;
      list.appendChild(item);
    }
  }

  function renderJson(id, value) {
    document.getElementById(id).textContent = formatPretty(value);
  }

  function renderText(id, value) {
    document.getElementById(id).textContent = value;
  }

  function renderCompatDiagnostics(value) {
    if (compatDiagnostics) {
      compatDiagnostics.textContent = formatPretty(value);
    }
  }

  if (!window.__AXION__) {
    status.textContent = 'Axion bootstrap was not injected. Run with `cargo run --features servo-runtime`.';
    for (const id of ['app-info', 'native-api', 'custom-command', 'capability-denial', 'event-log', 'compat-diagnostics']) {
      renderText(id, 'Bridge unavailable');
    }
    return;
  }

  const axion = window.__AXION__;
  const diagnostics = axion.diagnostics;
  const formatPretty = (value) =>
    typeof diagnostics?.toPrettyJson === 'function'
      ? diagnostics.toPrettyJson(value)
      : JSON.stringify(value, null, 2);
  const installTextInputSelectionPatch = axion.compat?.installTextInputSelectionPatch;
  const hostEventLog = [];
  renderList('command-list', axion.commands);
  renderList('event-list', axion.events);
  renderList('host-event-list', axion.hostEvents);

  function renderHostEventLog(extra = {}) {
    renderJson('event-log', {
      ...extra,
      frontendEvents: axion.events,
      hostEvents: axion.hostEvents,
      hostEventLog,
    });
  }

  for (const name of axion.hostEvents) {
    axion.listen(name, (payload) => {
      hostEventLog.unshift({ name, payload, receivedAt: new Date().toISOString() });
      hostEventLog.splice(8);
      renderHostEventLog();
    });
  }

  if (typeof installTextInputSelectionPatch === 'function') {
    const patchTargets = [
      [compatInput, false],
      [compatTextarea, true],
    ];
    for (const [element, manualPointerSelection] of patchTargets) {
      if (!element) continue;
      installTextInputSelectionPatch(element, {
        manualPointerSelection,
        onStatus(message) {
          status.textContent = message;
        },
        onUpdate(snapshot) {
          renderCompatDiagnostics(snapshot);
        },
      });
    }
  } else {
    renderCompatDiagnostics({
      error: 'window.__AXION__.compat.installTextInputSelectionPatch is unavailable',
    });
  }

  if (compatTextarea) {
    compatTextarea.addEventListener('keydown', (event) => {
      if (event.key !== 'Tab') return;
      event.preventDefault();
      const start = compatTextarea.selectionStart ?? compatTextarea.value.length;
      const end = compatTextarea.selectionEnd ?? start;
      const value = compatTextarea.value;
      compatTextarea.value = `${value.slice(0, start)}\t${value.slice(end)}`;
      compatTextarea.selectionStart = start + 1;
      compatTextarea.selectionEnd = start + 1;
      renderCompatDiagnostics({
        ...(typeof diagnostics?.snapshotTextControl === 'function'
          ? diagnostics.snapshotTextControl(compatTextarea, { source: 'textarea-tab-handler' })
          : {
              targetId: compatTextarea.id,
              selectionStart: compatTextarea.selectionStart,
              selectionEnd: compatTextarea.selectionEnd,
              valueLength: compatTextarea.value.length,
              detail: { source: 'textarea-tab-handler' },
            }),
      });
    });
  }

  window.__AXION_GUI_SMOKE__ = async () => {
    const exportedAt = new Date();
    const checks = [];
    const pushCheck = (id, label, statusValue, detail) => {
      checks.push({ id, label, status: statusValue, detail });
    };
    const bridgeInfo =
      typeof diagnostics?.describeBridge === 'function' ? diagnostics.describeBridge() : null;

    pushCheck(
      'bridge.bootstrap',
      'Bridge bootstrap available',
      axion.ready === true ? 'pass' : 'fail',
      axion.ready === true ? axion.version : 'window.__AXION__.ready is false',
    );
    pushCheck(
      'bridge.diagnostics',
      'Bridge diagnostics available',
      diagnostics ? 'pass' : 'fail',
      diagnostics ? 'describeBridge/snapshotTextControl/toPrettyJson present' : 'diagnostics missing',
    );
    pushCheck(
      'bridge.compat.text_input',
      'Input compat helper available',
      typeof axion.compat?.installTextInputSelectionPatch === 'function' ? 'pass' : 'fail',
      typeof axion.compat?.installTextInputSelectionPatch === 'function'
        ? 'installTextInputSelectionPatch'
        : 'compat helper missing',
    );
    pushCheck(
      'window.lifecycle.ready',
      'window.ready host event exposed',
      axion.hostEvents.includes('window.ready') ? 'pass' : 'fail',
      axion.hostEvents.includes('window.ready') ? 'window.ready' : 'missing window.ready',
    );

    let ping = null;
    let appInfo = null;
    let appVersion = null;
    let windowInfo = null;
    let greeting = null;

    try {
      ping = await axion.invoke('app.ping', { from: `${appName}-gui-smoke` });
      pushCheck('app.ping', 'app.ping', ping?.message === 'pong' ? 'pass' : 'fail', ping?.message ?? 'missing pong');
    } catch (error) {
      pushCheck('app.ping', 'app.ping', 'fail', error instanceof Error ? error.message : String(error));
    }

    try {
      appInfo = await axion.invoke('app.info', null);
      pushCheck('app.info', 'app.info', appInfo?.appName === appName ? 'pass' : 'fail', appInfo?.appName ?? 'missing appName');
    } catch (error) {
      pushCheck('app.info', 'app.info', 'fail', error instanceof Error ? error.message : String(error));
    }

    try {
      appVersion = await axion.invoke('app.version', null);
      pushCheck('app.version', 'app.version', appVersion?.framework === 'axion' ? 'pass' : 'fail', appVersion?.release ?? 'missing release');
    } catch (error) {
      pushCheck('app.version', 'app.version', 'fail', error instanceof Error ? error.message : String(error));
    }

    try {
      windowInfo = await axion.invoke('window.info', null);
      pushCheck('window.info', 'window.info', windowInfo?.id ? 'pass' : 'fail', windowInfo?.id ?? 'missing window id');
    } catch (error) {
      pushCheck('window.info', 'window.info', 'fail', error instanceof Error ? error.message : String(error));
    }

    try {
      greeting = await axion.invoke('demo.greet', { from: `${appName}-gui-smoke` });
      pushCheck('demo.greet', 'demo.greet', greeting?.message ? 'pass' : 'fail', greeting?.message ?? 'missing greeting');
    } catch (error) {
      pushCheck('demo.greet', 'demo.greet', 'fail', error instanceof Error ? error.message : String(error));
    }

    const inputSnapshot =
      typeof diagnostics?.snapshotTextControl === 'function'
        ? diagnostics.snapshotTextControl(compatInput, { source: 'gui-smoke' })
        : null;
    pushCheck(
      'input.snapshot',
      'Text control snapshot',
      inputSnapshot && inputSnapshot.targetId === 'compat-input' ? 'pass' : 'fail',
      inputSnapshot ? inputSnapshot.targetId : 'snapshotTextControl unavailable',
    );

    const result = checks.some((check) => check.status === 'fail') ? 'failed' : 'ok';
    return {
      schema: diagnostics?.reportSchema ?? bridgeInfo?.diagnosticsReportSchema ?? 'axion.diagnostics-report.v1',
      source: 'axion-vanilla-template',
      exported_at: exportedAt.toISOString(),
      exported_at_unix_seconds: Math.floor(exportedAt.getTime() / 1000),
      manifest_path: null,
      app_name: appInfo?.appName ?? appName,
      identifier: appInfo?.identifier ?? null,
      version: appInfo?.version ?? null,
      description: appInfo?.description ?? null,
      authors: Array.isArray(appInfo?.authors) ? appInfo.authors : [],
      homepage: appInfo?.homepage ?? null,
      mode: appInfo?.mode ?? 'production',
      window_count: windowInfo ? 1 : 0,
      windows: windowInfo
        ? [{
            id: windowInfo.id,
            title: windowInfo.title,
            bridge_enabled: true,
            configured_commands: [...axion.commands],
            configured_events: [...axion.events],
            configured_protocols: [axion.protocol ?? 'axion'],
            runtime_command_count: axion.commands.length,
            runtime_event_count: axion.events.length,
            host_events: [...axion.hostEvents],
            trusted_origins: [...axion.trustedOrigins],
            allowed_navigation_origins: [],
            allow_remote_navigation: false,
            width: windowInfo.width,
            height: windowInfo.height,
            resizable: windowInfo.resizable,
            visible: windowInfo.visible,
            focused: windowInfo.focused,
          }]
        : [],
      frontend_dist: null,
      entry: bridgeInfo?.locationHref ?? window.location.href,
      configured_dialog_backend: null,
      dialog_backend: null,
      icon: null,
      host_events: [...axion.hostEvents],
      staged_app_dir: null,
      asset_manifest_path: null,
      artifacts_removed: null,
      result,
      diagnostics: {
        bridge: bridgeInfo,
        app_version: appVersion,
        greeting,
        smoke_checks: checks,
        compat_input: inputSnapshot,
      },
    };
  };

  try {
    const pluginReady = new Promise((resolve) => {
      const timeout = window.setTimeout(() => resolve({ source: 'demo-plugin', observed: false }), 1500);
      axion.listen('demo.ready', (payload) => {
        window.clearTimeout(timeout);
        resolve({ source: payload.source, observed: true });
      });
    });

    const [ping, appInfo, appVersion, appEcho, windowInfo] = await Promise.all([
      axion.invoke('app.ping', { from: appName }),
      axion.invoke('app.info', null),
      axion.invoke('app.version', null),
      axion.invoke('app.echo', { from: appName, async: true }),
      axion.invoke('window.info', null),
    ]);
    const windowTitleUpdate = await axion.invoke('window.set_title', {
      title: `${windowInfo.title} · Axion`,
    });
    const windowSizeUpdate = await axion.invoke('window.set_size', {
      width: Math.max(windowInfo.width, 960),
      height: Math.max(windowInfo.height, 720),
    });

    renderJson('app-info', {
      bridge: typeof diagnostics?.describeBridge === 'function' ? diagnostics.describeBridge() : null,
      ping,
      appInfo,
      appVersion,
      appEcho,
      windowInfo,
      windowTitleUpdate,
      windowSizeUpdate,
    });

    const fsWrite = await axion.invoke('fs.write_text', {
      path: 'notes/hello.txt',
      contents: `${appName} wrote this through the Axion bridge`,
    });
    const fsRead = await axion.invoke('fs.read_text', { path: 'notes/hello.txt' });
    const dialogOpen = await axion.invoke('dialog.open', {
      title: 'Select files for the Axion preview',
      multiple: true,
      filters: [
        { name: 'Text', extensions: ['txt', 'md'] },
        { name: 'Images', extensions: ['png', 'jpg'] },
      ],
    });
    const dialogSave = await axion.invoke('dialog.save', {
      title: 'Choose a save path for the Axion preview',
      defaultPath: 'notes/export.txt',
    });
    renderJson('native-api', { fsWrite, fsRead, dialogOpen, dialogSave });

    const [greeting, pluginEvent] = await Promise.all([
      axion.invoke('demo.greet', { from: `${appName}-frontend` }),
      pluginReady,
    ]);
    renderJson('custom-command', { greeting, pluginEvent });

    const deniedCommand = await axion.invoke('demo.missing', null)
      .then(() => 'unexpected success')
      .catch((error) => error instanceof Error ? error.message : String(error));
    renderJson('capability-denial', {
      attemptedCommand: 'demo.missing',
      result: deniedCommand,
      explanation: 'Commands must be registered and allowed in axion.toml before frontend code can invoke them.',
    });

    const hostLog = axion.events.includes('app.log')
      ? await axion.emit('app.log', { message: `${appName} frontend is ready`, windowId: windowInfo.id })
      : false;
    renderHostEventLog({
      emitted: hostLog,
    });

    status.textContent = `Axion bridge ready: ${ping.message} from ${ping.appName}; custom=${greeting.message}`;
  } catch (error) {
    status.textContent = `Axion invoke failed: ${error instanceof Error ? error.message : String(error)}`;
    renderText('event-log', status.textContent);
  }
});
"#
        .replace("@APP_NAME@", &self.name)
    }
}

impl NewTemplate {
    fn name(self) -> &'static str {
        match self {
            Self::Vanilla => "vanilla",
        }
    }
}

fn axion_root_for_templates() -> Result<PathBuf, AxionCliError> {
    let cli_manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    if let Some(axion_root) = cli_manifest_dir
        .parent()
        .and_then(Path::parent)
        .filter(|path| path.join("crates").join("axion-core").exists())
    {
        return Ok(axion_root.to_path_buf());
    }

    Ok(std::env::current_dir()?)
}

fn normalize_project_name(name: &str) -> String {
    let normalized = name
        .trim()
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '-' {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_owned();

    if normalized.is_empty() {
        "axion-app".to_owned()
    } else {
        normalized
    }
}

fn title_case(name: &str) -> String {
    name.split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::{NewProject, axion_root_for_templates, normalize_project_name, title_case};
    use crate::cli::NewTemplate;

    #[test]
    fn project_name_is_normalized_for_package_use() {
        assert_eq!(normalize_project_name("Hello Axion!"), "hello-axion");
        assert_eq!(normalize_project_name("  "), "axion-app");
    }

    #[test]
    fn title_case_expands_kebab_name() {
        assert_eq!(title_case("hello-axion"), "Hello Axion");
    }

    #[test]
    fn template_axion_root_points_at_checkout_root() {
        let root = axion_root_for_templates().expect("template root should resolve");
        assert!(root.join("crates").join("axion-core").exists());
    }

    #[test]
    fn generated_frontend_uses_external_script_for_csp() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("unused"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        assert!(
            project
                .index_html()
                .contains("<script src=\"app.js\"></script>")
        );
        assert!(
            project
                .index_html()
                .contains("<link rel=\"stylesheet\" href=\"style.css\">")
        );
        assert!(!project.index_html().contains("window.addEventListener"));
        assert!(project.app_js().contains("window.addEventListener"));
        assert!(project.app_js().contains("axion.emit('app.log'"));
        assert!(project.app_js().contains("axion.invoke('demo.greet'"));
        assert!(project.app_js().contains("axion.invoke('demo.missing'"));
        assert!(project.app_js().contains("installTextInputSelectionPatch"));
        assert!(project.app_js().contains("describeBridge"));
        assert!(project.app_js().contains("snapshotTextControl"));
        assert!(project.app_js().contains("textarea-tab-handler"));
        assert!(project.app_js().contains("window.set_title"));
        assert!(project.app_js().contains("window.set_size"));
        assert!(project.app_js().contains("dialog.open"));
        assert!(project.app_js().contains("dialog.save"));
        assert!(project.app_js().contains("window.__AXION_GUI_SMOKE__"));
        assert!(project.app_js().contains("axion-vanilla-template"));
        assert!(project.app_js().contains("input.snapshot"));
        assert!(project.index_html().contains("compat-input"));
        assert!(project.index_html().contains("compat-textarea"));
        assert!(project.index_html().contains("compat-diagnostics"));
        assert!(project.style_css().contains(".field"));
        assert!(project.style_css().contains(".grid"));
    }

    #[test]
    fn generated_project_includes_custom_command_plugin() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("unused"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        assert!(project.manifest().contains("\"demo.greet\""));
        assert!(project.manifest().contains("\"app-info\""));
        assert!(project.manifest().contains("\"window-control\""));
        assert!(project.manifest().contains("\"file-access\""));
        assert!(project.manifest().contains("\"dialog-access\""));
        assert!(project.manifest().contains("\"app-events\""));
        assert!(project.manifest().contains("[bundle]"));
        assert!(project.manifest().contains("icon = \"icons/app.icns\""));
        assert!(project.manifest().contains("[native.dialog]"));
        assert!(project.manifest().contains("backend = \"headless\""));
        assert!(project.manifest().contains("# [dev]"));
        assert!(
            project
                .manifest()
                .contains("# url = \"http://127.0.0.1:3000\"")
        );
        assert!(
            project
                .manifest()
                .contains("# command = \"python3 -m http.server 3000")
        );
        assert!(project.manifest().contains("# timeout_ms = 15000"));
        assert!(project.main_rs().contains("struct DemoPlugin"));
        assert!(
            project
                .main_rs()
                .contains("register_command(\"demo.greet\"")
        );
        assert!(project.main_rs().contains("run_with_plugins"));
        assert!(project.main_rs().contains("json_string_literal"));
        assert!(project.main_rs().contains("install_panic_reporter"));
        assert!(project.main_rs().contains("target"));
        assert!(project.main_rs().contains("crash-reports"));
    }

    #[test]
    fn generated_project_readme_documents_template_and_commands() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("/tmp/hello-axion"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        let readme = project.readme();
        assert!(readme.contains("Generated by Axion using the `vanilla` template."));
        assert!(readme.contains("cargo run -- --plan"));
        assert!(readme.contains("cargo run --features servo-runtime"));
        assert!(readme.contains("Frontend Development"));
        assert!(readme.contains("cargo run -p axion-cli -- dev"));
        assert!(readme.contains("--watch --reload"));
        assert!(readme.contains("window.ready"));
        assert!(readme.contains("--open-devtools"));
        assert!(readme.contains("cargo run -p axion-cli -- gui-smoke"));
        assert!(readme.contains("cargo run -p axion-cli -- check"));
        assert!(readme.contains("--deny-warnings --max-risk medium"));
        assert!(readme.contains("--cargo-target-dir target"));
        assert!(readme.contains("--serial-build"));
        assert!(readme.contains("cargo run -p axion-cli -- bundle"));
        assert!(readme.contains("--build-executable"));
        assert!(readme.contains("Packaging Preview"));
        assert!(readme.contains("verification: ok"));
        assert!(readme.contains("fingerprinted_files"));
        assert!(readme.contains("Custom Command Demo"));
        assert!(readme.contains("demo.greet"));
        assert!(readme.contains("Capability denial"));
        assert!(readme.contains("Input Compatibility Demo"));
        assert!(readme.contains("installTextInputSelectionPatch"));
        assert!(readme.contains("window.__AXION_GUI_SMOKE__()"));
        assert!(readme.contains("frontend/style.css"));
        assert!(readme.contains("dialog.open"));
        assert!(readme.contains("Runtime Artifacts"));
        assert!(readme.contains("target/axion/crash-reports/"));
        assert!(readme.contains(".gitignore"));
        assert!(readme.contains("icons/app.icns"));
    }

    #[test]
    fn generated_project_template_includes_icon_asset() {
        assert!(super::TEMPLATE_APP_ICON.starts_with(b"icns"));
    }

    #[test]
    fn generated_project_gitignore_covers_local_artifacts() {
        let root = axion_root_for_templates().expect("template root should resolve");
        let project = NewProject {
            name: "hello-axion".to_owned(),
            root: std::path::PathBuf::from("unused"),
            axion_root: root,
            template: NewTemplate::Vanilla,
        };

        let gitignore = project.gitignore();
        assert!(gitignore.lines().any(|line| line == "target/"));
        assert!(gitignore.lines().any(|line| line == ".DS_Store"));
        assert!(gitignore.lines().any(|line| line == "*.log"));
    }
}
